spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/db_single_hospital_application
spring.datasource.username =root
spring.datasource.password=Karan@2000


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

whatsapp.token=EAAOFLVXRp4wBRXJ7j6Xv5LskfooForzIzZBvbB1aMZB82Rt6bQ6ZAt3lssaWS411K3q6ZCmmCLjJJJHtb8ZAkCmZBa4reiFgK9QusoYZC5JDn8yw3n7lrgViIUjZBbefnVykHYc7ladu8MElvmN0l2sJEt4FuQzUZBXfZBqv3Cu5TzVbAUKFZBRhkuiNnQWI07svD55yUbcY4WHZAK20cyVLZCqeOXPrwz8G2IJdCQWuR3elDtDfbRpPYZB58hrx9hDQdWOnGZAQIdrNxnqZCMlpV84NSuUy3gZDZD
whatsapp.phone-number-id=1105860942608516
whatsapp.verify-token=my_verify_token