spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/db_single_hospital_application
spring.datasource.username =root
spring.datasource.password=Karan@2000


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

whatsapp.token=EAAOFLVXRp4wBRYhjIGw4GSIZCoFoEfagNrxAZBdiRY2dZBoNcn7SW5YS2EsGQKRFXL15ARUNtR03Dhsmy4lZA5MsU06TH8PR5bZCdDwI3vZCOZCezcGOf47XZBTulKgLJUfRuuSExpGTivqhjyxAzCsTw282nc9pQrt37IJZCxqLsWaIqYRP2lMw7ZA0njdOTgkhEReXXYot9O8vYguywjh6hLoxslkW5tZBDvguZAlTCXyXZAnZCCCHZBk91FxjiaHBzxv6iHvtVZB39Xzfx4RbmktUMReD
whatsapp.phone-number-id=1105860942608516
whatsapp.verify-token=my_verify_token