spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/db_single_hospital_application
spring.datasource.username =root
spring.datasource.password=Karan@2000


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

whatsapp.token=EAAOFLVXRp4wBRcsCfhj9PRUWbIZC5t93aie9Woi4AaXeTvUlawqslrG75TG74Rs7qsLnucmnjMiQrycogCQf4LtpVHUWhFHIv6nTAQvCuSxI37PeHNe47SF4rukZCRIi8aj6zQMaoJ5ZBd6Xy99WkKEb7olJFvcRWhHSJOAZC4aAGaiF0sS9Q66Xz7dNb3bw38iZB9ZCNJPZB5WRgFbZA1rgnMOL866wNEc1zafvRpEHGxlolIzphZBqLC1OT5zvgSdGEZA1f510lopviamURslXcx
whatsapp.phone-number-id=1105860942608516
whatsapp.verify-token=my_verify_token